
package com.soa2.logisticstatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LogisticsInterface", targetNamespace = "http://services.soa2.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogisticsInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.soa2.logiticstatus.Logistics
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.soa2.com/LogisticsInterface/getLogisticsStatusRequest", output = "http://services.soa2.com/LogisticsInterface/getLogisticsStatusResponse")
    public Logistics getLogisticsStatus(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
